class datatypes:
    CCL_CHAR = 0
    CCL_SIGNED_CHAR = 1
    CCL_UNSIGNED_CHAR = 2
    CCL_BYTE = 3
    CCL_WCHAR = 4
    CCL_SHORT = 5
    CCL_UNSIGNED_SHORT = 6
    CCL_INT = 7
    CCL_UNSIGNED = 8
    CCL_LONG = 9
    CCL_UNSIGNED_LONG = 10
    CCL_FLOAT = 11
    CCL_DOUBLE = 12
    CCL_LONG_DOUBLE = 13
    CCL_LONG_LONG_INT = 14
    CCL_UNSIGNED_LONG_LONG = 15
    CCL_LONG_LONG = 16